name: Deploy to GAE

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Deploy to App Engine
      id: deploy
      run: |
        gcloud auth activate-service-account --key-file=${{ secrets.GCP_CREDENTIALS }}
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud app deploy --quiet