name: Deploy to GAE

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  deploy:
    name: Deploying to Google Cloud
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Connect to gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Change file permissions
      run: chmod 0755 *

    - name: Deploy to GAE
      run: |
            gcloud app deploy --quiet